2021-03-13 14:31:32,712 INFO    MainThread:24441 [wandb_setup.py:_flush():69] setting env: {}
2021-03-13 14:31:32,712 INFO    MainThread:24441 [wandb_setup.py:_flush():69] setting login settings: {}
2021-03-13 14:31:32,712 INFO    MainThread:24441 [wandb_init.py:_log_setup():334] Logging user logs to /Users/amalota/Documents/mgr/DRL-XAI-POC/wandb/run-20210313_143132-1qtfnwsg/logs/debug.log
2021-03-13 14:31:32,713 INFO    MainThread:24441 [wandb_init.py:_log_setup():335] Logging internal logs to /Users/amalota/Documents/mgr/DRL-XAI-POC/wandb/run-20210313_143132-1qtfnwsg/logs/debug-internal.log
2021-03-13 14:31:32,714 INFO    MainThread:24441 [wandb_init.py:_jupyter_setup():285] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fcd02c9d160>
2021-03-13 14:31:32,714 INFO    MainThread:24441 [wandb_init.py:init():367] calling init triggers
2021-03-13 14:31:32,714 INFO    MainThread:24441 [wandb_init.py:init():372] wandb.init called with sweep_config: {}
config: {}
2021-03-13 14:31:32,714 INFO    MainThread:24441 [wandb_init.py:init():416] starting backend
2021-03-13 14:31:32,715 INFO    MainThread:24441 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-03-13 14:31:32,731 INFO    MainThread:24441 [backend.py:ensure_launched():123] starting backend process...
2021-03-13 14:31:32,739 INFO    MainThread:24441 [backend.py:ensure_launched():127] started backend process with pid: 24460
2021-03-13 14:31:32,744 INFO    MainThread:24441 [wandb_init.py:init():421] backend started and connected
2021-03-13 14:31:32,785 INFO    MainThread:24441 [wandb_init.py:init():461] updated telemetry
2021-03-13 14:31:32,785 INFO    MainThread:24441 [wandb_init.py:init():480] communicating current version
2021-03-13 14:31:33,511 INFO    MainThread:24441 [wandb_init.py:init():485] got version response upgrade_message: "wandb version 0.10.22 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-03-13 14:31:33,512 INFO    MainThread:24441 [wandb_init.py:init():493] communicating run to backend with 30 second timeout
2021-03-13 14:31:33,792 INFO    MainThread:24441 [wandb_init.py:init():518] starting run threads in backend
2021-03-13 14:31:35,435 INFO    MainThread:24441 [wandb_run.py:_console_start():1476] atexit reg
2021-03-13 14:31:35,435 INFO    MainThread:24441 [wandb_run.py:_redirect():1339] redirect: SettingsConsole.WRAP
2021-03-13 14:31:35,436 INFO    MainThread:24441 [wandb_run.py:_redirect():1374] Wrapping output streams.
2021-03-13 14:31:35,436 INFO    MainThread:24441 [wandb_run.py:_redirect():1390] Redirects installed.
2021-03-13 14:31:35,436 INFO    MainThread:24441 [wandb_init.py:init():542] run started, returning control to user process
2021-03-13 14:31:35,438 INFO    MainThread:24441 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-13 14:31:35,438 INFO    MainThread:24441 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-13 14:31:39,965 INFO    MainThread:24441 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-13 14:31:40,326 INFO    MainThread:24441 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-13 14:31:40,326 INFO    MainThread:24441 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-13 14:31:42,732 INFO    MainThread:24441 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-13 14:32:11,571 INFO    MainThread:24441 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-13 14:32:11,571 INFO    MainThread:24441 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-13 14:32:14,567 INFO    MainThread:24441 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-13 14:32:43,220 INFO    MainThread:24441 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-13 14:32:43,220 INFO    MainThread:24441 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-13 14:33:19,944 INFO    MainThread:24441 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-13 14:33:52,109 INFO    MainThread:24441 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-13 14:33:52,109 INFO    MainThread:24441 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-13 14:33:52,114 INFO    MainThread:24441 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-13 14:33:52,253 INFO    MainThread:24441 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-13 14:33:52,253 INFO    MainThread:24441 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-13 14:34:24,840 INFO    MainThread:24441 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-13 14:34:24,843 INFO    MainThread:24441 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-13 14:34:24,843 INFO    MainThread:24441 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-13 14:36:35,788 INFO    MainThread:24441 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-13 14:36:35,797 INFO    MainThread:24441 [wandb_setup.py:_flush():69] setting env: {}
2021-03-13 14:36:35,797 INFO    MainThread:24441 [wandb_setup.py:_flush():69] setting login settings: {}
2021-03-13 14:36:35,798 INFO    MainThread:24441 [wandb_init.py:_log_setup():334] Logging user logs to /Users/amalota/Documents/mgr/DRL-XAI-POC/wandb/run-20210313_143635-112j2tj7/logs/debug.log
2021-03-13 14:36:35,798 INFO    MainThread:24441 [wandb_init.py:_log_setup():335] Logging internal logs to /Users/amalota/Documents/mgr/DRL-XAI-POC/wandb/run-20210313_143635-112j2tj7/logs/debug-internal.log
2021-03-13 14:36:35,798 INFO    MainThread:24441 [wandb_init.py:init():367] calling init triggers
2021-03-13 14:36:35,798 INFO    MainThread:24441 [wandb_init.py:init():372] wandb.init called with sweep_config: {}
config: {}
2021-03-13 14:36:35,798 INFO    MainThread:24441 [wandb_init.py:init():387] re-initializing run, found existing run on stack: 1qtfnwsg
2021-03-13 14:36:35,799 INFO    MainThread:24441 [wandb_run.py:finish():1135] finishing run malota/deep-rl-tf2/1qtfnwsg
